class PacketId:
    DISCONNECT = 0x07
    UNCONNECTED_PING = 0x01
    UNCONNECTED_PONG = 0x02
    CLIENT_ACCEPT_CONNECTION = 0x03
    CLIENT_REQUEST_CONNECTION = 0x04
    CLIENT_OPEN_CONNECTION = 0x05
    CLIENT_OPEN_CONNECTIONREPLY = 0x06

